apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db2-backup
  namespace: db2-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
