apiVersion: v1
kind: Service
metadata:
  name: my-db2-svc
  namespace: demo
  labels:
    app: db2
spec:
  ports:
    - port: 50010
      name: db2-port
  clusterIP: None   # Headless service, required for StatefulSet
  selector:
    app: db2