apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db2
  namespace: demo
spec:
  serviceName: "my-db2-svc"
  replicas: 2
  selector:
    matchLabels:
      app: db2
  template:
    metadata:
      labels:
        app: db2
    spec:
      containers:
        - name: db2
          securityContext:
            privileged: true
          image: ibmcom/db2:11.5.8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50000
              name: db2-port
          env:
            - name: LICENSE
              value: "accept"

          volumeMounts:
            - name: db2-data
              mountPath: /database
  volumeClaimTemplates:
    - metadata:
        name: db2-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
        storageClassName: local-path

