apiVersion: kubedb.com/v1alpha2
kind: DocumentDB
metadata:
  name: dcdb-tls-ha
  namespace: demo
spec:
  version: pg17-0.109.0
  replicas: 3
  sslMode: verify-full
  tls:
    tls:
      issuerRef:
        apiGroup: cert-manager.io
        kind: Issuer
        name: dcdb-ca-issuer
  podTemplate:
    spec:
      enableServiceLinks: false
  storageType: Durable
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-path
  deletionPolicy: WipeOut
