apiVersion: v1
kind: ConfigMap
metadata:
  name: hadr-config  # Must match hadrConfig.name
  namespace: demo
data:
    my-db2-instance: |
      primary: 0
      standby: 1
      serviceTemplates:
        - alias: primary
          spec:
            type: LoadBalancer
    
