apiVersion: catalog.kubedb.com/v1alpha1
kind: DB2Version
metadata:
  name: 11.5.8.0
spec:
  coordinator:
    image: sabnaj/db2-coordinator:db2-script
  db:
    image: ibmcom/db2:11.5.8.0
  version: "11.5.8.0"