apiVersion: v1
kind: Service
metadata:
  name: db2
  namespace: db2-system
  labels:
    app: db2
spec:
  ports:
    - port: 50000
      name: db2-port
  clusterIP: None   # Headless service, required for StatefulSet
  selector:
    app: db2