apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db2
  namespace: db2-system
spec:
  serviceName: "db2"
  replicas: 2
  selector:
    matchLabels:
      app: db2
  template:
    metadata:
      labels:
        app: db2
    spec:
      containers:
        - name: db2
          securityContext:
            privileged: true
          image: ibmcom/db2:11.5.8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50000
              name: db2-port
          env:
            - name: DB2INST1_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db2-secrets
                  key: DB2INST1_PASSWORD
            - name: LICENSE
              value: "accept"
          volumeMounts:
            - name: db2-data
              mountPath: /database
            - name: db2-backup
              mountPath: /database/backup  # shared backup folder
      volumes:
        - name: db2-backup
          persistentVolumeClaim:
            claimName: db2-backup
  volumeClaimTemplates:
    - metadata:
        name: db2-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
        storageClassName: local-path

