apiVersion: catalog.kubedb.com/v1alpha1
kind: DocumentDBVersion
metadata:
  name: '17.0'
spec:
  db:
    image: sabnaj/documentdb-local-vim:latest
  version: '17.0'
  scripts:
    image: sabnaj/documentdb-init:_linux_amd64
