apiVersion: v1
kind: Service
metadata:
  name: documentdb-gateway
  namespace: demo
spec:
  selector:
    app: documentdb-gateway
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
  type: ClusterIP