apiVersion: ops.kubedb.com/v1alpha1
kind: DocumentDBOpsRequest
metadata:
  name: dcdb-rtls-ha-rotate-tls
  namespace: demo
spec:
  type: ReconfigureTLS
  databaseRef:
    name: dcdb-rtls-ha
  tls:
    rotateCertificates: true
