apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: dcdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: app
          image: ghcr.io/documentdb/documentdb/documentdb-local:latest
          imagePullPolicy: IfNotPresent
          ports:
              - containerPort: 10260
                name: documentdb-port
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: documentdb-credentials
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: documentdb-credentials
                  key: password
