apiVersion: v1
kind: Secret
metadata:
  name: new-custom-config
  namespace: demo
type: Opaque
stringData:
  mongod.conf: |
    storage:
      dbPath: /data/db

    net:
      port: 27017
      bindIp: 0.0.0.0

    setParameter:
      enableLocalhostAuthBypass: false