apiVersion: v1
kind: Pod
metadata:
  name: db2-pod-0
  labels:
    app: 0-db2
spec:
  securityContext:
    fsGroup: 1000


  containers:
    - name: db2
      image: ibmcom/db2:11.5.8.0
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true

      ports:
        - containerPort: 50000
          name: db2

      env:
        - name: LICENSE
          value: "accept"
        - name: DB2INSTANCE
          value: "db2inst1"
        - name: DB2INST1_PASSWORD
          value: "password"
        #        - name: DBNAME
        #          value: "testdb"
        - name: ARCHIVE_LOGS
          value: "false"
        - name: AUTOCONFIG
          value: "false"

      volumeMounts:
        - name: db2-storage
          mountPath: /database
  #      resources:
  #        requests:
  #          memory: "2Gi"
  #          cpu: "1"
  #        limits:
  #          memory: "4Gi"
  #          cpu: "2"
  volumes:
    - name: db2-storage
      persistentVolumeClaim:
        claimName: 0-db2-pvc
