apiVersion: kubedb.com/v1alpha2
kind: Cassandra
metadata:
  name: cassandra-quickstart
  namespace: demo
spec:
  deletionPolicy: Delete
  topology:
    rack:
    - name: r0
      replicas: 2
      storage:
        storageClassName: "local-path"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 600Mi
  version: 5.0.7
